name 'nodejs_windows'
maintainer 'Gene Gotimer'
maintainer_email 'gene.gotimer@coveros.com'
license 'All Rights Reserved'
description 'Installs Node.js on Windows'
long_description 'Installs Node.js on Windows'
version '0.1.0'
supports 'windows', '2012R2'
supports 'windows', '2016'
chef_version '>= 12.1' if respond_to?(:chef_version)
